- hosts: masters
  remote_user: centos
  sudo: yes
  vars:
    etcd_ip: "master.mesos"
    etcd_port: 2379

  tasks:

  - name: make sure docker-python is not installed via yum
    yum:
      name: docker-python
      state: absent

  - name: make sure epel-release is installed
    yum:
      name: epel-release
      state: present

  - name: make sure pip is installed
    yum:
      name: python-pip
      state: present

  - name: make sure docker-py is installed via pip
    pip: name="docker-py==1.10.6" state=present

  - name: start etcd
    docker_container:
      name: etcd
      network_mode: host
      image: quay.io/coreos/etcd:v3.1.10
      command: etcd --advertise-client-urls "http://{{ etcd_ip }}:{{ etcd_port }}" --listen-client-urls "http://{{ etcd_ip }}:{{ etcd_port }},http://127.0.0.1:{{ etcd_port }}"
      state: started
      recreate: yes
      restart: no

  - name: download calicoctl
    get_url: url="https://github.com/projectcalico/calicoctl/releases/download/v1.6.1/calicoctl" dest=/usr/bin/calicoctl mode=0755 force=yes

- hosts: agents:agent_publics:masters
  remote_user: centos
  sudo: yes
  vars:
    etcd_ip: "master.mesos"
    etcd_port: 2379

  tasks:

  - name: start calico-node
    shell: sudo docker rm /calico-node -f | true && sudo docker run -d --restart=always --net=host --privileged --name=calico-node -e FELIX_IGNORELOOSERPF=true -v /lib/modules:/lib/modules -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock -e CALICO_LIBNETWORK_ENABLED=true -e IP=$(/opt/mesosphere/bin/detect_ip) -e HOSTNAME=$(hostname) -e ETCD_ENDPOINTS=http://{{ etcd_ip }}:{{ etcd_port }} -e ETCD_SCHEME=http quay.io/calico/node:v2.6.2

  - name: download calico
    get_url: url="https://github.com/projectcalico/cni-plugin/releases/download/v1.5.5/calico" dest=/opt/mesosphere/active/cni/calico mode=0755 force=yes
    when: "'masters' not in group_names"

  - name: download calico-ipam
    get_url: url="https://github.com/projectcalico/cni-plugin/releases/download/v1.5.5/calico-ipam" dest=/opt/mesosphere/active/cni/calico-ipam mode=0755 force=yes
    when: "'masters' not in group_names"

  - name: configure calico
    template: src=templates/calico.cni.j2 dest=/opt/mesosphere/etc/dcos/network/cni/calico.cni mode=0644
    when: "'masters' not in group_names"

  - name: restart agent
    service:
      name: dcos-mesos-slave
      state: restarted
    when: "'agents' in group_names"
    ignore_errors: true

  - name: restart agent_public
    service:
      name: dcos-mesos-slave-public
      state: restarted
    when: "'agent_publics' in group_names"
    ignore_errors: true

  - name: restart navstar
    service:
      name: dcos-navstar
