- hosts: agents:agents_public:masters
  remote_user: centos
  become: true
  vars:
    elastic_hostname: "master.elastic.l4lb.thisdcos.directory"
    elastic_port: 9200
    kibana_hostname: "web.kibana.marathon.l4lb.thisdcos.directory"
    kibana_port: 80

  tasks:

  - name: install filebeat
    yum:
      name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.0.0-x86_64.rpm
      state: present

  - name: create dcos log directory
    file: path=/var/log/dcos state=directory mode=0744

  - name: configure filebeat
    template: src=templates/filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml mode=0644

  - name: configure filebeat systemd service
    template: src=templates/dcos-journalctl-filebeat.service.j2 dest=/etc/systemd/system/dcos-journalctl-filebeat.service mode=0755

  - name: configure logrotation
    blockinfile:
      dest: "{{ item }}"
      state: present
      create: yes
      block: |
        /var/log/dcos/dcos.log {
          size 1M
          copytruncate
          rotate 5
          compress
          compresscmd /bin/xz
        }
    with_items:
      - /opt/mesosphere/etc/logrotate_master.config
      - /opt/mesosphere/etc/logrotate_agent.config

  - name: start dcos-journalctl-filebeat.service
    systemd:
      name: dcos-journalctl-filebeat.service
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: start filebeat
    systemd:
      name: filebeat
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: restart dcos-logrotate-master.service
    systemd:
      name: dcos-logrotate-master.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    when: "'masters' in group_names"

  - name: restart dcos-logrotate-agent.service
    systemd:
      name: dcos-logrotate-agent.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    when: "'masters' not in group_names"
